version: "3.8"
services:
  api:
    build: ./
      # context: ./build
      # dockerfile: Dockerfile-dev  //if dockerfile is named differently
    networks:
      - connection_network
    ports:
      - 4000:4000
    env_file:
      - ./env/api.env
    volumes:
      - ./src:/app/src
      # - logs:/app/logs
      # - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres
    networks:
      - connection_network
    ports:
      - 5432:5432
    env_file:
      - ./env/postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src:/app/src
  # frontend:
  #   build: ./frontend
  #   ports: 
  #     - 3000:3000    
  #   volumes:
  #     - ./frontend/src:/app/src
  #   container_name: frontend
  #   stdin_open: true
  #   tty: true  
  #   depends_on:
  #     - api

volumes:
  pgdata:
    driver: local
networks:
  connection_network:
    driver: bridge
