version: "3.8"
services:
  api:
    build: ./
    networks:
      - connection_network
    ports:
      - 4000:4000
    environment:
      - SECRET_KEY=sammykightgfhgcvbnb
      - PORT=4000
      - NODE_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appointments_db
      - POSTGRES_DIALECT=postgres
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  db:
    image: postgres
    networks:
      - connection_network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appointments_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src:/app/src

volumes:
  pgdata:
    driver: local
networks:
  connection_network:
    driver: bridge
