version: "3.8"
services:
  api:
    build: ./
    networks:
      - connection_network
    ports:
      - 4000:4000
    env_file:
      - ./env/api.env
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  db:
    image: postgres
    networks:
      - connection_network
    ports:
      - 5432:5432
    env_file:
      - ./env/postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src:/app/src

volumes:
  pgdata:
    driver: local
networks:
  connection_network:
    driver: bridge
